os: linux
dist: xenial
language: python
python:
  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-dev.txt

cache:
  - pip

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    # - stage: "PreCommit"
    #   name: "PreCommit rules check"
    #   env: CAN_FAIL=true
    #   script: pre-commit run --all-files

    # - stage: "test"
    #   name: "Run tests"
    #   script:
    #     - coverage run --omit 'venv/*' -m py.test
    #     - bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      name: "Deploy GH-Docs"
      script:
        - cd docs
        - make html
        - make html
        - ls docs/build
      deploy:
        provider: pages # deploy on github pages
        project_name: BleNaviPy
        github_token: "$GITHUB_TOKEN"
        local_dir: docs/build/html
        on:
          branch:
            - ci/docs
