os: linux
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install -r requirements-dev.txt

cache:
  - pip

jobs:
  include:
    - stage: preCommit
      name: "PreCommit rules check"
      script: pre-commit run --all-files

    - stage: test
      name: "Run tests and upload the status"
      script:
        - coverage run --omit 'venv/*','tests/*' -m py.test
        - bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      branches:
        only:
          - development
      if: (NOT type IN (pull_request)) AND (branch = development)
      name: "Deploy GH-Docs"
      script:
        - docstr-coverage -m -P bleNaviPy -b docs/build/html/doc_coverage
        - cd docs
        - make html
        - make html
        - cd ..
      deploy:
        provider: pages # deploy on github pages
        project_name: BleNaviPy
        github_token: "$GITHUB_TOKEN"
        local_dir: docs/build/html
        edge: true
        on:
          branch:
            - development
