os: linux
dist: xenial
language: python
cache: pip
python:
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo "Installing"
  - pip install -r requirements-dev.txt
  - pip install coveralls

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    - stage: "linting"
      env: CAN_FAIL=true
      script: black --check .
    - stage: "test"
      script:
        - coverage run -m pytest
        - coveralls
