os:
  - linux
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "2.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo "Installing"
  - pip install -r requirements_test.txt

script:
  # - python setup.py nosetests --with-coverage --cover-package easydev
  - echo "Testing"

after_success:
  - echo "Coveralls"
  - coveralls
